apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | quote }}
  labels: {{- include "db_charts.labels" . | nindent 4 }}
spec:
  selector:
    #since pod labels should all match
    {{- include "db_charts.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}