# Default values for db_charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8081
  name: mongo-express-service
  targetPort: 8081
  nodePort: 30000

container:
  name: mongodb

secret:
  name: mongodb-secret
  username: bXNoYWxsb20=
  password: Q2hhbW8uUHpv
