apiVersion: apps/v1
kind: Deployment
metadata:
#   name: {{ .Release.Name }}
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: {{ .Values.containers.expname }}
        image: {{ .Values.expressimage.repository }}
        imagePullPolicy: {{ .Values.expressimage.pullPolicy }}
        ports:
          - containerPort: {{ .Values.externalservice.targetPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
