version: '3'
services:
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb


  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME="${DB_HOST}"
      - MONGO_INITDB_ROOT_PASSWORD="${DB_PASSWORD}"
    volumes:
      - mongo-vol:/data/db


volumes:
  mongo-vol:
    driver: local