name: 'Stale issue handler'
on: [push]

jobs:
  print_output_job:
      runs-on: ubuntu-latest
      needs: [stale_job]
      steps:        
        - name: Print OS-name 
          run: |
            cat /etc/os-release

        - name: List all files in the directory
          run: |
            ls ${{github.workspace}}
