name: 'Output config'

on: 
  push:
    branches:
      - main

jobs:

  print_output_job:
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v3
      - name: Print OS-name 
        run: |
          cat /etc/os-release

      - name: List all files in the directory
        run: |
          ls ${{github.workspace}}
